### ISSUE TITLE
Migrate preprocessed data files from json to yaml ?

### ISSUE THREAD

**Issue by NathanCHEVALIER** [NathanCHEVALIER/epimap#58]
JSON:
```json
{
    "kb": {
        "name": "Kremlin-Bicêtre",
        "last_update": "Sep. 2021",
        "buildings": {
            "voltaire": {
                "name": "Voltaire",
                "last_update": "",
                "floors": {
                    "kb-voltaire-f-1": {
                        "name": "Voltaire - Sous-sol",
                        "last_update": "Apr. 2022",
                        "floor": "-1",
                        "rooms": {}
                    },
                    "kb-voltaire-f0": {
                        "name": "Voltaire - Rez de Chaussée",
                        "last_update": "Feb. 2023",
                        "floor": "0",
                        "rooms": {
                            "accueil": {
                                "name": "Accueil",
                                "description": null,
                                "tenant": "epita",
                                "image": "",
                                "peoples": ["julie.ounoughi"],
                                "tags": ["accueil", "adm"]
                            },
                            "scolarite-ing": {
                                "name": "Scolarité Cycle Ingénieur",
                                "description": "Aka. Le SPA",
                                "tenant": "epita",
                                "image": "",
                                "peoples": ["florent.boullet"],
                                "tags": ["adm", "scola"]
                            }
                        }
                   }
              }
         }
    }
}

```

YAML:

```yml

kb:
  name: Kremlin-Bicêtre
  last_update: Sep. 2021
  buildings:
    voltaire:
      name: Voltaire
      last_update: ''
      floors:
        kb-voltaire-f-1:
          name: Voltaire - Sous-sol
          last_update: Apr. 2022
          floor: "-1"
          rooms: {}
        kb-voltaire-f0:
          name: Voltaire - Rez de Chaussée
          last_update: Feb. 2023
          floor: '0'
          rooms:
            accueil:
              name: Accueil
              description:
              tenant: epita
              image: ''
              peoples:
              - julie.ounoughi
              tags:
              - accueil
              - adm
            scolarite-ing:
              name: Scolarité Cycle Ingénieur
              description: Aka. Le SPA
              tenant: epita
              image: ''
              peoples:
              - florent.boullet
              tags:
              - adm
              - scola
```
